FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# No COPY . .  <-- IMPORTANT

EXPOSE 8000

# In dev we do NOT run entrypoint.sh (no migrations on hot reload)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
