"""added daily pair table

Revision ID: 6628f53d9ae9
Revises: a4ba0d23c3c1
Create Date: 2026-01-24 13:57:41.241161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6628f53d9ae9'
down_revision: Union[str, Sequence[str], None] = 'a4ba0d23c3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_pairs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paired_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paired_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('date', 'user_id')
    )
    op.create_index(op.f('ix_daily_pairs_date'), 'daily_pairs', ['date'], unique=False)
    op.create_index(op.f('ix_daily_pairs_paired_user_id'), 'daily_pairs', ['paired_user_id'], unique=False)
    op.create_index(op.f('ix_daily_pairs_user_id'), 'daily_pairs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_pairs_user_id'), table_name='daily_pairs')
    op.drop_index(op.f('ix_daily_pairs_paired_user_id'), table_name='daily_pairs')
    op.drop_index(op.f('ix_daily_pairs_date'), table_name='daily_pairs')
    op.drop_table('daily_pairs')
    # ### end Alembic commands ###
