"""fixed user model, added relationship to dump

Revision ID: 6635aca2db28
Revises: 95b9857a2d11
Create Date: 2025-12-15 12:40:28.290475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6635aca2db28'
down_revision: Union[str, Sequence[str], None] = '95b9857a2d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dumps', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dumps', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dumps', type_='foreignkey')
    op.drop_column('dumps', 'user_id')
    # ### end Alembic commands ###
