"""added back embeddings

Revision ID: 9ba5586fd1cd
Revises: b8fc429e414f
Create Date: 2025-12-12 10:35:22.828200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9ba5586fd1cd'
down_revision: Union[str, Sequence[str], None] = 'b8fc429e414f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('embedding', Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'embedding')
    # ### end Alembic commands ###
