"""initial tables

Revision ID: b34a95073bfe
Revises: 
Create Date: 2025-12-05 13:02:41.352846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b34a95073bfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True)
,
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('dumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dumps_id'), 'dumps', ['id'], unique=False)
    op.create_index(op.f('ix_dumps_text'), 'dumps', ['text'], unique=False)
    op.create_table('thoughts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaned_text', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True)
,
    sa.Column('dump_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dump_id'], ['dumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thoughts_cleaned_text'), 'thoughts', ['cleaned_text'], unique=False)
    op.create_index(op.f('ix_thoughts_id'), 'thoughts', ['id'], unique=False)
    op.create_index(op.f('ix_thoughts_raw_text'), 'thoughts', ['raw_text'], unique=False)
    op.create_table('thoughts_categories',
    sa.Column('thought_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.PrimaryKeyConstraint('thought_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thoughts_categories')
    op.drop_index(op.f('ix_thoughts_raw_text'), table_name='thoughts')
    op.drop_index(op.f('ix_thoughts_id'), table_name='thoughts')
    op.drop_index(op.f('ix_thoughts_cleaned_text'), table_name='thoughts')
    op.drop_table('thoughts')
    op.drop_index(op.f('ix_dumps_text'), table_name='dumps')
    op.drop_index(op.f('ix_dumps_id'), table_name='dumps')
    op.drop_table('dumps')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
